-- Menu content matched to the live Foodics menu.
--
-- GENERATED by backend/db/tools/import-foodics-menu.mjs — do not hand-edit.
-- Rerun that script and commit the result when the Foodics menu changes.
--
-- Items are never deleted: booking_items references menu_items, so removing a
-- row would break the line items on past orders. Everything is withdrawn
-- (available = false) and then re-published by name, which both preserves that
-- history and lets staff bring an old item back from the editor.
BEGIN;

ALTER TABLE menu_items
  ADD COLUMN IF NOT EXISTS name_ar        TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description_ar TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS section        TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS section_ar     TEXT    NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS display_order  INTEGER NOT NULL DEFAULT 0;

-- Anything not on the new menu simply stops being offered.
UPDATE menu_items SET available = FALSE;

INSERT INTO menu_items
  (name, name_ar, category, price_cents, description, description_ar,
   section, section_ar, display_order, available)
SELECT v.name, v.name_ar, v.category, v.price_cents, v.description, v.description_ar,
       v.section, v.section_ar, v.display_order, TRUE
  FROM (VALUES
  ('Espresso', 'إسبريسو', 'drink', 100, '', '', 'Coffee', 'قهوة', 1),
  ('Americano', 'أمريكانو', 'drink', 135, 'A smooth, full-bodied Americano with rich espresso mellowed by hot water for a balanced, comforting cup.', 'A smooth, full-bodied Americano with rich espresso mellowed by hot water for a balanced, comforting cup.', 'Coffee', 'قهوة', 2),
  ('Ice Americano', 'آيس أمريكانو', 'drink', 145, '', '', 'Coffee', 'قهوة', 3),
  ('Cappuccino', 'كابتشينو', 'drink', 140, '', '', 'Coffee', 'قهوة', 4),
  ('Latte', 'لاتيه', 'drink', 140, '', '', 'Coffee', 'قهوة', 5),
  ('Spanish Latte', 'سبانش لاتيه', 'drink', 205, '', '', 'Coffee', 'قهوة', 6),
  ('Salted Caramel Latte', 'لاتيه كراميل مالح', 'drink', 175, '', '', 'Coffee', 'قهوة', 7),
  ('Mocha', 'موكا', 'drink', 175, '', '', 'Coffee', 'قهوة', 8),
  ('White Mocha', 'وايت موكا', 'drink', 175, '', '', 'Coffee', 'قهوة', 9),
  ('Cold Brew', 'كولد برو', 'drink', 190, 'Smooth, slow-steeped cold brew coffee with rich, mellow flavors and a naturally refreshing finish.', 'Smooth, slow-steeped cold brew coffee with rich, mellow flavors and a naturally refreshing finish.', 'Coffee', 'قهوة', 10),
  ('Affogatto', 'أفوغاتو', 'drink', 190, '', '', 'Coffee', 'قهوة', 11),
  ('Flat White', 'فلات وايت', 'drink', 140, '', '', 'Coffee', 'قهوة', 12),
  ('Cortado', 'كورتادو', 'drink', 150, '', '', 'Coffee', 'قهوة', 13),
  ('V60', 'في ٦٠', 'drink', 195, '', '', 'Coffee', 'قهوة', 14),
  ('Iced V60', 'آيس V60', 'drink', 205, 'A bright, refreshing iced V60 pour-over with crisp acidity and clean, nuanced flavors.', 'A bright, refreshing iced V60 pour-over with crisp acidity and clean, nuanced flavors.', 'Coffee', 'قهوة', 15),
  ('Turkish Coffee', 'قهوة تركية', 'drink', 150, '', '', 'Coffee', 'قهوة', 16),
  ('French Coffee', 'قهوة فرنسية', 'drink', 150, '', '', 'Coffee', 'قهوة', 17),
  ('Lemon Iced Tea', 'شاي مثلج بالليمون', 'drink', 175, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 18),
  ('Peach Iced Tea', 'شاي مثلج بالخوخ', 'drink', 175, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 19),
  ('English Breakfast - Black Tea', 'شاي إنجلش بريكفست أسود', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 20),
  ('Green Tea - Finest Leaf', 'شاي أخضر – أوراق فاخرة', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 21),
  ('Jasmine Tea', 'شاي ياسمين', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 22),
  ('Cinnamon Tea - Black Tea', 'شاي أسود بالقرفة', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 23),
  ('Chamomile & Lemon Grass - Herbal Tea', 'شاي أعشاب بابونج وليمون غراس', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 24),
  ('Tea Blend', 'شاي بلِند (خلطة شاي)', 'drink', 250, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 25),
  ('Karak Tea', 'شاي كرك', 'drink', 100, '', '', 'Hot/Iced Tea', 'شاي مثلج/حار', 26),
  ('Iced Matcha Latte', 'لاتيه ماتشا مثلج', 'drink', 195, '', '', 'Matcha', 'ماتشا', 27),
  ('Hot Matcha Latte', 'لاتيه ماتشا ساخن', 'drink', 195, 'A creamy hot matcha latte with earthy green tea notes, delicately balanced and soothing in every sip.', 'A creamy hot matcha latte with earthy green tea notes, delicately balanced and soothing in every sip.', 'Matcha', 'ماتشا', 28),
  ('Matcha Lemonade', 'ماتشا ليمونادة', 'drink', 215, '', '', 'Matcha', 'ماتشا', 29),
  ('Passionista', 'باشونيستا', 'drink', 225, 'Passion Fruit Puree
Mint
Lemon
Sparkling Water', 'Passion Fruit Puree
Mint
Lemon
Sparkling Water', 'Mocktails', 'موكتيل', 30),
  ('Coconut Lychee Splash', 'سبلاش جوز هند لايتشي', 'drink', 250, 'Coconut
Lychee
Lemon
Peach
Sparkling Water', 'Coconut
Lychee
Lemon
Peach
Sparkling Water', 'Mocktails', 'موكتيل', 31),
  ('Pinky Sour', 'بينكي ساور', 'drink', 250, 'Sparkling Water
Lemon
Rose', 'Sparkling Water
Lemon
Rose', 'Mocktails', 'موكتيل', 32),
  ('Cozytini', 'كوزيتيني', 'drink', 250, 'Milk
Double Espresso
Cheesecake Syrup
Caramel', 'Milk
Double Espresso
Cheesecake Syrup
Caramel', 'Mocktails', 'موكتيل', 33),
  ('After 8', 'أفتر ٨', 'drink', 250, 'Milk
Espresso
Chocolate
Mint', 'Milk
Espresso
Chocolate
Mint', 'Mocktails', 'موكتيل', 34),
  ('One Night Vampire Mocktail', 'ون نايت فامباير', 'drink', 225, 'Green Cola Lemon
Blue Curacao
Strawberry
Mint', 'Green Cola Lemon
Blue Curacao
Strawberry
Mint', 'Mocktails', 'موكتيل', 35),
  ('Mojito', 'موهيتو', 'drink', 200, 'Lemon
Mint
Sparkling Water', 'Lemon
Mint
Sparkling Water', 'Mocktails', 'موكتيل', 36),
  ('Orange Blossom', 'زهرة البرتقال', 'drink', 250, 'Fresh Orange Juice
Coconut
Triple Sec
Lemon', 'Fresh Orange Juice
Coconut
Triple Sec
Lemon', 'Mocktails', 'موكتيل', 37),
  ('Hello Green', 'هيلو جرين', 'drink', 225, 'Green Apple
Lychee
Lemon
Sparkling
Garnished with home dehydrated apples', 'Green Apple
Lychee
Lemon
Sparkling
Garnished with home dehydrated apples', 'Mocktails', 'موكتيل', 38),
  ('Sassy', 'ساسي', 'drink', 325, 'Rooibos & Cinnamon Tea
Black Cherry
Blueberry
Lemon
Aquafaba 
Garnished with pansy flower & fresh blue berries', 'Rooibos & Cinnamon Tea
Black Cherry
Blueberry
Lemon
Aquafaba 
Garnished with pansy flower & fresh blue berries', 'Mocktails', 'موكتيل', 39),
  ('Pristine Quencher', 'بريستين كوينشر', 'drink', 250, 'Watermelon
Mint
Lemon
Aquafaba
Water', 'Watermelon
Mint
Lemon
Aquafaba
Water', 'Mocktails', 'موكتيل', 40),
  ('Tropical Punch', 'تروبيكال بنش', 'drink', 225, 'Mango
Lychee
Triple Sec
Sparkling Water', 'Mango
Lychee
Triple Sec
Sparkling Water', 'Mocktails', 'موكتيل', 41),
  ('Raspberry Breeze', 'راسبيري بريز (نسيم التوت)', 'drink', 250, '', '', 'Mocktails', 'موكتيل', 42),
  ('Redbull Mocktail', 'موكتيل ريدبول', 'drink', 225, '', '', 'Mocktails', 'موكتيل', 43),
  ('Blue Moon', 'بلو مون', 'drink', 275, 'An enchanting mocktail crafted with Sea Arch, lychee purée, lime cordial, and a splash of blue curaçao.
Topped with a delicate smoke bubble that forms the shape of a glowing moon – a visual and flavorful experience.', 'An enchanting mocktail crafted with Sea Arch, lychee purée, lime cordial, and a splash of blue curaçao.
Topped with a delicate smoke bubble that forms the shape of a glowing moon – a visual and flavorful experience.', 'Mocktails', 'موكتيل', 44),
  ('PinaLemo', 'بيناليـمو', 'drink', 250, 'Sparkling Water
Raspberry
Lemon
Mint', 'Sparkling Water
Raspberry
Lemon
Mint', 'Mocktails', 'موكتيل', 45),
  ('Blueberry Redbull Mojito', 'موهيتو ريدبول بالتوت الأزرق', 'drink', 250, '', '', 'Mocktails', 'موكتيل', 46),
  ('Crimson Echo - SUGAR-FREE', 'صدى قرمزي – خالي من السكر', 'drink', 275, 'A vibrant hibiscus tea infused with sugar-free red berry syrup and fresh lemon, lightly sweetened for a crisp, refreshing finish.', 'A vibrant hibiscus tea infused with sugar-free red berry syrup and fresh lemon, lightly sweetened for a crisp, refreshing finish.', 'Sugar-Free Mocktails', 'موكتيل بدون سكر', 47),
  ('Martini Fizz - SUGAR-FREE', 'مارتيني فِز – خالي من السكر', 'drink', 275, 'A refreshing, alcohol-free blend of Sea Arch Juniper with tropical passion mango, a hint of vanilla, and fresh lemon, delicately sweetened for a crisp, botanical finish.', 'A refreshing, alcohol-free blend of Sea Arch Juniper with tropical passion mango, a hint of vanilla, and fresh lemon, delicately sweetened for a crisp, botanical finish.', 'Sugar-Free Mocktails', 'موكتيل بدون سكر', 48),
  ('Green Spark - SUGAR-FREE', 'الشرارة الخضراء – خالي من السكر', 'drink', 275, 'A crisp, energizing fusion of Diet Red Bull with sugar-free green apple and peach apricot notes, brightened by a splash of fresh lemon for a refreshing, guilt-free boost.', 'A crisp, energizing fusion of Diet Red Bull with sugar-free green apple and peach apricot notes, brightened by a splash of fresh lemon for a refreshing, guilt-free boost.', 'Sugar-Free Mocktails', 'موكتيل بدون سكر', 49),
  ('Sunset Bliss - SUGAR-FREE', 'بهجة الغروب – خالي من السكر', 'drink', 275, 'A refreshing sugar-free passion peach iced tea infused with tropical mango, a hint of vanilla, and a splash of fresh lemon for a perfectly balanced finish.', 'A refreshing sugar-free passion peach iced tea infused with tropical mango, a hint of vanilla, and a splash of fresh lemon for a perfectly balanced finish.', 'Sugar-Free Mocktails', 'موكتيل بدون سكر', 50),
  ('Fresh Orange Juice', 'عصير برتقال طازج', 'drink', 125, '', '', 'Juices', 'عصائر', 51),
  ('Lemonade', 'ليمونادة', 'drink', 115, '', '', 'Juices', 'عصائر', 52),
  ('Vanilla Milkshake', 'ميلك شيك فانيلا', 'drink', 150, '', '', 'Milkshakes', 'ميلك شيك', 53),
  ('Cappucino Milkshake', 'ميلك شيك كابتشينو', 'drink', 200, '', '', 'Milkshakes', 'ميلك شيك', 54),
  ('Kinder Bueno Milkshake', 'ميلك شيك كيندر بوينو', 'drink', 225, '', '', 'Milkshakes', 'ميلك شيك', 55),
  ('Green Cola Original 330ml', 'جرين كولا أصلي ٣٣٠ مل', 'drink', 75, '', '', 'Soft Drinks', 'مشروبات غازية', 56),
  ('Green Cola Lemon 330ml', 'جرين كولا ليمون ٣٣٠ مل', 'drink', 75, '', '', 'Soft Drinks', 'مشروبات غازية', 57),
  ('Green Cola Cherry 330ml', 'جرين كولا كرز ٣٣٠ مل', 'drink', 75, '', '', 'Soft Drinks', 'مشروبات غازية', 58),
  ('Green Cola Orange 330ml', 'جرين كولا برتقال ٣٣٠ مل', 'drink', 75, '', '', 'Soft Drinks', 'مشروبات غازية', 59),
  ('Green Cola Mocktails - Passion Fruit', 'جرين كولا موكتيل – فاكهة العاطفة', 'drink', 100, '', '', 'Soft Drinks', 'مشروبات غازية', 60),
  ('Green Cola Mocktails - Pink Grape', 'جرين كولا موكتيل – جريب فروت وردي', 'drink', 100, '', '', 'Soft Drinks', 'مشروبات غازية', 61),
  ('Green Cola Mocktails - Pomegranate', 'جرين كولا موكتيل – رمان', 'drink', 100, '', '', 'Soft Drinks', 'مشروبات غازية', 62),
  ('Fevertree Ginger Ale', 'فيفرتري جينجر إيل', 'drink', 75, '', '', 'Soft Drinks', 'مشروبات غازية', 63),
  ('Flash 250ml', 'فلاش ٢٥٠ مل', 'drink', 65, '', '', 'Soft Drinks', 'مشروبات غازية', 64),
  ('Flash Cherry 250ml', 'Flash Cherry 250ml', 'drink', 65, '', '', 'Soft Drinks', 'مشروبات غازية', 65),
  ('Flash Mix', 'فلاش ميكس', 'drink', 100, '', '', 'Soft Drinks', 'مشروبات غازية', 66),
  ('Eva Aqua Water 500ml', 'مياه إيفا أكوا ٥٠٠ مل', 'drink', 50, '', '', 'Other Drinks', 'مشروبات اخرى', 67),
  ('Voss Sparkling Water', 'مياه غازية فوس', 'drink', 100, '', '', 'Other Drinks', 'مشروبات اخرى', 68),
  ('Glass of Milk', 'حليب', 'drink', 75, '', '', 'Other Drinks', 'مشروبات اخرى', 69),
  ('Iced Chocolate', 'شوكولاتة مثلجة', 'drink', 150, '', '', 'Other Drinks', 'مشروبات اخرى', 70),
  ('Hot Chocolate', 'شوكولاتة ساخنة', 'drink', 195, 'Rich, velvety hot chocolate crafted from premium cocoa, delivering a smooth, indulgent warmth in every sip.', 'Rich, velvety hot chocolate crafted from premium cocoa, delivering a smooth, indulgent warmth in every sip.', 'Other Drinks', 'مشروبات اخرى', 71),
  ('QminC Ginger & Honey 150ml', 'مشروب زنجبيل وعسل QminC ١٥٠ مل', 'drink', 65, '', '', 'Other Drinks', 'مشروبات اخرى', 72),
  ('Glass of Lussory White Premium Non Alcoholic', 'كوب لوسوري أبيض فاخر بدون كحول', 'drink', 125, '', '', 'Other Drinks', 'مشروبات اخرى', 73),
  ('Glass of Lussory Red Premium Non Alcoholic', 'كوب لوسوري أحمر فاخر بدون كحول', 'drink', 125, '', '', 'Other Drinks', 'مشروبات اخرى', 74),
  ('Redbull with Ice', 'ريدبول مع ثلج', 'drink', 115, '', '', 'Other Drinks', 'مشروبات اخرى', 75),
  ('Diet Redbull with Ice', 'دايت ريدبول مع ثلج', 'drink', 115, '', '', 'Other Drinks', 'مشروبات اخرى', 76),
  ('Redbull Mix', 'ريدبول ميكس', 'drink', 165, '', '', 'Other Drinks', 'مشروبات اخرى', 77),
  ('Diet Redbull Mix', 'دايت ريدبول ميكس', 'drink', 165, '', '', 'Other Drinks', 'مشروبات اخرى', 78),
  ('Chicken Ceasar Salad', 'سلطة دجاج سيزر', 'food', 275, '', '', 'Salads', 'سلطات', 79),
  ('Signature Chicken Salad', 'سلطة دجاج سيغنتشر', 'food', 275, '', '', 'Salads', 'سلطات', 80),
  ('Chicken Fillet', 'فيليه دجاج', 'food', 185, '', '', 'Chicken', 'دجاج', 81),
  ('Zinger Supreme', 'زنجر سوبريم', 'food', 200, '', '', 'Chicken', 'دجاج', 82),
  ('Chipotle Chicken Fillet', 'فيليه دجاج شيبوتلي', 'food', 200, '', '', 'Chicken', 'دجاج', 83),
  ('Air Baked Twister', 'تويستر مشوي بالهواء', 'food', 185, 'Air-baked crispy chicken wrapped in a soft, lightly toasted tortilla, layered with fresh crunchy lettuce, juicy diced tomatoes, and finished with a smooth, creamy garlic sauce.', 'Air-baked crispy chicken wrapped in a soft, lightly toasted tortilla, layered with fresh crunchy lettuce, juicy diced tomatoes, and finished with a smooth, creamy garlic sauce.', 'Chicken', 'دجاج', 84),
  ('Chicken Ceasar Wrap', 'راب دجاج سيزر', 'food', 175, '', '', 'Chicken', 'دجاج', 85),
  ('The Red Panda', 'The Red Panda', 'food', 215, 'Crispy golden chicken fillet layered with melted cheddar cheese and smoky deli turkey, topped with fresh lettuce and finished with a creamy chipotle-style sauce, all served in a soft, toasted brioche bun.', 'Crispy golden chicken fillet layered with melted cheddar cheese and smoky deli turkey, topped with fresh lettuce and finished with a creamy chipotle-style sauce, all served in a soft, toasted brioche bun.', 'Chicken', 'دجاج', 86),
  ('Chicken Popcorn', 'بوبكورن دجاج', 'food', 125, '', '', 'Chicken', 'دجاج', 87),
  ('Chicken Nuggets 6pcs', '٦ قطع ناغتس دجاج', 'food', 100, '', '', 'Chicken', 'دجاج', 88),
  ('4x Chicken Strips', '٤ أصابع دجاج', 'food', 125, '', '', 'Chicken', 'دجاج', 89),
  ('Classic Burger', 'برجر كلاسيك', 'food', 185, '', '', 'Beef Burgers', 'برجر لحم', 90),
  ('Smoke House Burger', 'برجر سموك هاوس', 'food', 235, '', '', 'Beef Burgers', 'برجر لحم', 91),
  ('Mushroom & Swiss Burger', 'برجر مشروم وسويس', 'food', 220, '', '', 'Beef Burgers', 'برجر لحم', 92),
  ('Chipotle Burger', 'برجر شيبوتلي', 'food', 200, '', '', 'Beef Burgers', 'برجر لحم', 93),
  ('Classic Burger Combo', 'برجر كلاسيك مع بطاطس', 'food', 235, '', '', 'Combo', 'كومبو', 94),
  ('Smoke House Burger Combo', 'برجر سموك هاوس مع بطاطس', 'food', 285, '', '', 'Combo', 'كومبو', 95),
  ('Mushroom & Swiss Burger Combo', 'برجر مشروم وسويس مع بطاطس', 'food', 270, '', '', 'Combo', 'كومبو', 96),
  ('Chipotle Burger Combo', 'كومبو برجر شيبوتلي', 'food', 250, '', '', 'Combo', 'كومبو', 97),
  ('Air Baked Twister Combo', 'تويستر مشوي بالهواء مع بطاطس', 'food', 235, '', '', 'Combo', 'كومبو', 98),
  ('Chicken Fillet Combo', 'Chicken Fillet Combo', 'food', 235, '', '', 'Combo', 'كومبو', 99),
  ('Zinger Supreme Combo', 'زنجر سوبريم مع بطاطس', 'food', 250, '', '', 'Combo', 'كومبو', 100),
  ('Chipotle Chicken Fillet Combo', 'كومبو فيليه دجاج شيبوتلي', 'food', 250, '', '', 'Combo', 'كومبو', 101),
  ('The Red Panda Combo', 'The Red Panda Combo', 'food', 265, 'Crispy golden chicken fillet layered with melted cheddar cheese and smoky deli turkey, topped with fresh lettuce and finished with a creamy chipotle-style sauce, all served in a soft, toasted brioche bun.', 'Crispy golden chicken fillet layered with melted cheddar cheese and smoky deli turkey, topped with fresh lettuce and finished with a creamy chipotle-style sauce, all served in a soft, toasted brioche bun.', 'Combo', 'كومبو', 102),
  ('Chicken Katsu Curry with Fries', 'دجاج كاتسو كاري مع بطاطس', 'food', 270, '', '', 'Katsu Curry', 'كاتسو كاري', 103),
  ('Chicken Katsu Curry w/ Rice & Salad', 'دجاج كاتسو كاري مع رز وسلطة', 'food', 325, '', '', 'Katsu Curry', 'كاتسو كاري', 104),
  ('Samyang Spicy Chicken Ramen Cup - Black', 'نودلز ساميانغ حار دجاج – أسود', 'food', 150, '', '', 'Instant Ramen', 'رامن', 105),
  ('Samyang Spicy Chicken Ramen Cup - Pink', 'نودلز ساميانغ حار دجاج – وردي', 'food', 150, '', '', 'Instant Ramen', 'رامن', 106),
  ('Samyang Spicy Chicken Ramen Cup - Green', 'نودلز ساميانغ حار دجاج – أخضر', 'food', 150, '', '', 'Instant Ramen', 'رامن', 107),
  ('Samyang Spicy Chicken Ramen Cup - Red', 'نودلز ساميانغ حار دجاج – أحمر', 'food', 150, '', '', 'Instant Ramen', 'رامن', 108),
  ('Loaded Buldak Ramen', 'لوديد بولدوك نودلز', 'food', 325, 'Creamy carbonara buldak noodles loaded with melted cheddar and mozzarella, topped with crispy chicken strips, crunchy onions, spring onions, and sesame seeds.', 'Creamy carbonara buldak noodles loaded with melted cheddar and mozzarella, topped with crispy chicken strips, crunchy onions, spring onions, and sesame seeds.', 'Instant Ramen', 'رامن', 109),
  ('Chicken Nuggets Meal', 'وجبة دجاج ناجتس', 'food', 185, 'Six pieces of tender, air-baked chicken nuggets served with golden fries and a refreshing glass of lemonade', 'Six pieces of tender, air-baked chicken nuggets served with golden fries and a refreshing glass of lemonade', 'Kids Meal', 'وجبات الاطفال', 110),
  ('Chicken Strips Meal', 'وجبة دجاج ستريبس', 'food', 185, 'Two pieces of tender, air-baked chicken strips served with golden fries and a refreshing glass of lemonade', 'Two pieces of tender, air-baked chicken strips served with golden fries and a refreshing glass of lemonade', 'Kids Meal', 'وجبات الاطفال', 111),
  ('Smoke House Feast', 'وجبة سموك هاوس', 'food', 195, 'A hearty serving of air-baked golden fries and crispy onion rings, generously topped with crunchy fried onions and crispy beef bacon. Drizzled with smoky BBQ, creamy ranch, and our rich signature cheese sauce.', 'A hearty serving of air-baked golden fries and crispy onion rings, generously topped with crunchy fried onions and crispy beef bacon. Drizzled with smoky BBQ, creamy ranch, and our rich signature cheese sauce.', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 112),
  ('Loaded Fries', 'بطاطس مقلية محملة', 'food', 185, 'Air-baked golden fries topped with crispy onions, chicken popcorn, pickled jalapenos slices, drizzled in our signature sauces and rich cheese sauce.', 'Air-baked golden fries topped with crispy onions, chicken popcorn, pickled jalapenos slices, drizzled in our signature sauces and rich cheese sauce.', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 113),
  ('Air Baked Fries', 'بطاطس مقلية مشوية بالهواء', 'food', 95, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 114),
  ('Curly Fries', 'بطاطس مبرومة', 'food', 115, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 115),
  ('Onion Rings', 'حلقات بصل', 'food', 125, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 116),
  ('4x Mozzarella Sticks', '٤ أصابع موتزاريلا', 'food', 125, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 117),
  ('5x Cheese Bites', '٥ بايتس جبن', 'food', 135, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 118),
  ('5x Cheddar Cheese Stuffed Jalapeno Nuggets', '٥ قطع ناغتس هالابينو محشي جبنة شيدر', 'food', 135, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 119),
  ('4x Cheese Stuffed Whole Jalapeno', '٤ حبات فلفل هالابينو محشي جبن', 'food', 135, '', '', 'Air-Baked Sides', 'اطباق جانبية مقلية بالهواء', 120),
  ('Croissant Plain', 'كرواسون سادة', 'food', 95, '', '', 'Pastries', 'مخبوزات', 121),
  ('Croissant Cheddar Cheese', 'كرواسون جبنة شيدر', 'food', 110, '', '', 'Pastries', 'مخبوزات', 122),
  ('Croissant Zaatar', 'كرواسون زعتر', 'food', 105, '', '', 'Pastries', 'مخبوزات', 123),
  ('Turkey and Cheese Croissant', 'كرواسون ديك رومي وجبنة', 'food', 155, '', '', 'Pastries', 'مخبوزات', 124),
  ('Pan Au Chocolat', 'بان أو شوكولا', 'food', 135, '', '', 'Sweet Pastries', 'مخبوزات تحلية', 125),
  ('Almond Croissant', 'كرواسون لوز', 'food', 100, '', '', 'Sweet Pastries', 'مخبوزات تحلية', 126),
  ('Banoffee Danish', 'دانش بانوفـي', 'food', 145, '', '', 'Sweet Pastries', 'مخبوزات تحلية', 127),
  ('Berry Cheesecake Danish', 'دانش تشيزكيك توت', 'food', 145, '', '', 'Sweet Pastries', 'مخبوزات تحلية', 128),
  ('Double Chocolate Croissant', 'كرواسون شوكولاتة مزدوجة', 'food', 145, '', '', 'Sweet Pastries', 'مخبوزات تحلية', 129),
  ('Home-Made Brownie', 'براوني منزلي', 'food', 125, '', '', 'Dessert', 'حلويات', 130),
  ('Home-made Brownie w/ Ice Cream', 'براوني منزلي مع آيس كريم', 'food', 175, '', '', 'Dessert', 'حلويات', 131),
  ('Cozy Cake', 'كوزي كيك', 'food', 175, 'Velvety heart warming chocolate cake made with premium ingredients that would leave you wanting for more.
Inspired by the famous Matilda cake.', 'Velvety heart warming chocolate cake made with premium ingredients that would leave you wanting for more.
Inspired by the famous Matilda cake.', 'Dessert', 'حلويات', 132),
  ('Mini Red Velvet Cake', 'كيك رد فلفت صغير', 'food', 150, '', '', 'Dessert', 'حلويات', 133),
  ('2x Kinder Cookies', '٢ كوكيز كيندر', 'food', 125, '', '', 'Dessert', 'حلويات', 134),
  ('Nutella Cruffin', 'كرفن نوتيلا', 'food', 120, '', '', 'Dessert', 'حلويات', 135),
  ('Custard Cruffin', 'كرفن كاسترد', 'food', 120, '', '', 'Dessert', 'حلويات', 136),
  ('Kinder Donut', 'دونات كيندر', 'food', 125, '', '', 'Dessert', 'حلويات', 137),
  ('Custard Donut', 'دونات كاسترد', 'food', 125, '', '', 'Dessert', 'حلويات', 138),
  ('Nutella Donut', 'دونات نوتيلا', 'food', 125, '', '', 'Dessert', 'حلويات', 139),
  ('Glazed Donut', 'دونات مغطاة', 'food', 115, '', '', 'Dessert', 'حلويات', 140),
  ('Waffle', 'وافل', 'food', 250, 'Golden waffle drizzled with rich pistachio sauce and Nutella.
A perfect balance of crunchy, creamy, and chocolatey flavors.', 'وافل ذهبي مقرمش مغطى بصوص الفستق الغني والنوتيلا
مزيج مثالي من القرمشة والنكهة الغنية بالشوكولاتة', 'Dessert', 'حلويات', 141),
  ('Waffle w/ Ice Cream', 'وافل مع ابس كريم', 'food', 300, 'Golden waffle topped with creamy vanilla ice cream.
Finished with rich pistachio sauce and Nutella.', 'وافل ذهبي مقرمش مع آيس كريم الفانيلا الكريم.
مغطى بصوص الفستق الغني والنوتيلا.', 'Dessert', 'حلويات', 142),
  ('Soft Serve Ice Cream', 'آيس كريم', 'food', 125, '', '', 'Ice Cream', 'آيس كريم', 143),
  ('Ice Cream w/ Sauce', 'آيس كريم مع صلصة', 'food', 175, '', '', 'Ice Cream', 'آيس كريم', 144),
  ('Kinder Ice Cream', 'آيس كريم كيندر', 'food', 200, '', '', 'Ice Cream', 'آيس كريم', 145),
  ('Kinder Cookies Ice Cream', 'آيس كريم كوكيز كيندر', 'food', 250, '', '', 'Ice Cream', 'آيس كريم', 146),
  ('Mickey Mouse', 'ميكي ماوس', 'food', 250, 'A playful and refreshing blend of orange juice and pineapple purée, swirled with a creamy vanilla ice cream. Finished with a zest of orange and our signature home-dried orange slice for a magical touch.', 'A playful and refreshing blend of orange juice and pineapple purée, swirled with a creamy vanilla ice cream. Finished with a zest of orange and our signature home-dried orange slice for a magical touch.', 'Ice Cream', 'آيس كريم', 147),
  ('Fulfil Vitamin and Protein Bar - Chocolate & Salted Caramel', 'بار بروتين فولفيل بالشوكولاتة والكراميل المملح', 'food', 140, '', '', 'Snacks', 'Snacks', 148),
  ('Fulfil Vitamin and Protein Bar - Chocolate & Hazelnut', 'بار بروتين فولفيل بالشوكولاتة والبندق', 'food', 140, '', '', 'Snacks', 'Snacks', 149),
  ('Fulfil Vitamin and Protein Bar - Peanut & Caramel', 'بار بروتين فولفيل بالفول السوداني والكراميل', 'food', 140, '', '', 'Snacks', 'Snacks', 150),
  ('Fulfil Vitamin and Protein Bar - Dark Chocolate Salted Caramel', 'بار بروتين فولفيل شوكولاتة داكنة وكراميل مملح', 'food', 140, '', '', 'Snacks', 'Snacks', 151),
  ('Al-Rifai Salted Peanuts Packet 13g', 'فول سوداني مملح الرفاعي ١٣غ', 'food', 15, '', '', 'Snacks', 'Snacks', 152),
  ('Al-Rifai Salted Cashews 25g', 'كاجو مملح الرفاعي ٢٥غ', 'food', 29, '', '', 'Snacks', 'Snacks', 153),
  ('Al-Rifai Roasted Pistachios 25g', 'فستق محمص الرفاعي ٢٥غ', 'food', 29, '', '', 'Snacks', 'Snacks', 154),
  ('Al-Rifai Mixed Nuts 25g', 'مكسرات مشكلة الرفاعي ٢٥غ', 'food', 29, '', '', 'Snacks', 'Snacks', 155),
  ('Kinder Bueno', 'كيندر بوينو', 'food', 45, '', '', 'Snacks', 'Snacks', 156),
  ('Kinder Cards', 'كيندر كاردز', 'food', 45, '', '', 'Snacks', 'Snacks', 157),
  ('Kinder Surprise Egg', 'بيضة كيندر سربرايز', 'food', 50, '', '', 'Snacks', 'Snacks', 158),
  ('Kinder Happy Hippo', 'كيندر هيبي هيبو', 'food', 30, '', '', 'Snacks', 'Snacks', 159),
  ('Kinder Country', 'كيندر كانتري', 'food', 25, '', '', 'Snacks', 'Snacks', 160),
  ('Kinder Boy 4 Bars', 'كيندر بوي ٤ قطع', 'food', 40, '', '', 'Snacks', 'Snacks', 161),
  ('Kinder Joy', 'كيندر جوي', 'food', 45, '', '', 'Snacks', 'Snacks', 162),
  ('Kinder Bueno Mini Bag', 'كيندر بوينو ميني باج', 'food', 135, '', '', 'Snacks', 'Snacks', 163),
  ('Peppero Almonds', 'بيبيرو لوز', 'food', 55, '', '', 'Snacks', 'Snacks', 164),
  ('Loacker Red 45g', 'لوكر أحمر ٤٥غ', 'food', 35, '', '', 'Snacks', 'Snacks', 165),
  ('Nutella B Ready 22g', 'نوتيلا بي ريدي ٢٢غ', 'food', 25, '', '', 'Snacks', 'Snacks', 166),
  ('Nutella Go', 'نوتيلا جو', 'food', 75, '', '', 'Snacks', 'Snacks', 167),
  ('Funzels Pepero Chocolate', 'فنزلز بيبيرو شوكولاتة', 'food', 40, '', '', 'Snacks', 'Snacks', 168),
  ('Hello Panda', 'هيلو باندا', 'food', 25, '', '', 'Snacks', 'Snacks', 169),
  ('Caprice Medium', 'كابريس ميديم', 'food', 125, '', '', 'Snacks', 'Snacks', 170),
  ('Caprese Wafer Stuffed with Hazelnut 53g', 'ويفر كابريزي محشي بالبندق ٥٣غ', 'food', 95, '', '', 'Snacks', 'Snacks', 171),
  ('Sour Punk Mini Strawberry Sticks', 'عصي سور بانك ميني فراولة', 'food', 20, '', '', 'Snacks', 'Snacks', 172),
  ('Bebeto Strawberry Jelly', 'جيلي بيبيتو فراولة', 'food', 15, '', '', 'Snacks', 'Snacks', 173),
  ('Kitkat', 'Kitkat', 'food', 20, '', '', 'Snacks', 'Snacks', 174),
  ('Aero', 'Aero', 'food', 45, '', '', 'Snacks', 'Snacks', 175),
  ('Ulker Chocolate Havelnut Spread', 'سبريد شوكولاتة أولكر بالبندق', 'food', 30, '', '', 'Snacks', 'Snacks', 176),
  ('Barni Milk Cake', 'كيك بارني بالحليب', 'food', 35, '', '', 'Snacks', 'Snacks', 177),
  ('Chocolate Peanuts', 'فول سوداني بالشوكولاتة', 'food', 19, '', '', 'Snacks', 'Snacks', 178),
  ('Flying Dragon Jelly Candy', 'جيلي كاندي تنين طائر', 'food', 20, '', '', 'Snacks', 'Snacks', 179),
  ('Jelly Cola', 'جيلي كولا', 'food', 15, '', '', 'Snacks', 'Snacks', 180),
  ('Yup Pizza Jelly', 'جيلي بيتزا يوب', 'food', 15, '', '', 'Snacks', 'Snacks', 181),
  ('Fruits Jelly', 'جيلي فواكه', 'food', 95, '', '', 'Snacks', 'Snacks', 182),
  ('Roll Up Jelly', 'جيلي رول أب', 'food', 45, '', '', 'Snacks', 'Snacks', 183),
  ('Not Guilty Cola', 'نوت جيلتي كولا', 'food', 125, '', '', 'Snacks', 'Snacks', 184),
  ('Fruit by the Foot', 'Fruit by the Foot', 'food', 85, '', '', 'Snacks', 'Snacks', 185)
  ) AS v(name, name_ar, category, price_cents, description, description_ar,
         section, section_ar, display_order)
ON CONFLICT (name) DO UPDATE SET
  name_ar        = EXCLUDED.name_ar,
  category       = EXCLUDED.category,
  price_cents    = EXCLUDED.price_cents,
  description    = EXCLUDED.description,
  description_ar = EXCLUDED.description_ar,
  section        = EXCLUDED.section,
  section_ar     = EXCLUDED.section_ar,
  display_order  = EXCLUDED.display_order,
  available      = TRUE;

-- The menu page reads only what is on offer, in menu order.
CREATE INDEX IF NOT EXISTS menu_items_available_order
  ON menu_items (display_order) WHERE available;

COMMIT;
