-- The café's game library, imported from the staff's own categorisation sheet
-- ("تقسيمة الالعاب"): 327 titles across 15 categories.
--
-- The sheet carries a title and a category and nothing else, so player counts
-- arrive empty rather than invented — see the column change below. Staff fill
-- them in from the games editor, and a game without them simply shows no player
-- range instead of a wrong one.
BEGIN;

-- Player counts become optional. The existing CHECKs still hold for any game
-- that HAS numbers (a NULL makes a CHECK neither true nor false, so it passes),
-- which is exactly the rule wanted: if you give a range, it must make sense.
ALTER TABLE games ALTER COLUMN min_players DROP NOT NULL;
ALTER TABLE games ALTER COLUMN max_players DROP NOT NULL;

-- Titles are unique, so a game already in the library is re-filed under the
-- sheet's category and keeps everything staff have since added to it — its
-- description, its picture, its player counts.
INSERT INTO games (title, category)
VALUES
  ('Agent Avenue (Arabic)', '2 Players'),
  ('Agent Hunter', '2 Players'),
  ('BattleShip', '2 Players'),
  ('Guess Who', '2 Players'),
  ('Hive Carbon', '2 Players'),
  ('Lost Cities', '2 Players'),
  ('Mr. Jack', '2 Players'),
  ('Odin''s Ravens', '2 Players'),
  ('onitama', '2 Players'),
  ('Patchwork', '2 Players'),
  ('تابو', 'Challenge'),
  ('يالنكتة', 'Party Games'),
  ('On A Scale Of One To T-Rex', 'Challenge'),
  ('أوش', 'Challenge'),
  ('The Voting Game', 'Chat'),
  ('لو خيروك بين اثنين مالهم ثالث وش تختار', 'Chat'),
  ('شنو', 'Challenge'),
  ('تحدي المعرفة', 'Challenge'),
  ('Story Cubes', 'Chat'),
  ('More Or Less', 'Chat'),
  ('شنو الجعدة', 'Challenge'),
  ('جاوب خطأ', 'Challenge'),
  ('من صجك', 'Chat'),
  ('Allegra', 'Family'),
  ('Ice Breaker', 'Chat'),
  ('العراف', 'Challenge'),
  ('5 Second Rule', 'Challenge'),
  ('كلمة وحدة', 'Challenge'),
  ('مثلها', 'Party Games'),
  ('خنسولف', 'Chat'),
  ('FriendShip Edition', 'Chat'),
  ('We''re Not Really Strangers', 'Chat'),
  ('عرررفت', 'Challenge'),
  ('بس بالصوت', 'Party Games'),
  ('فلها', 'Party Games'),
  ('Truth Or Dare', 'Chat'),
  ('لا أي ولالا', 'Challenge'),
  ('شنو حرفك', 'Challenge'),
  ('Ito', 'Challenge'),
  ('Cobra Paw', 'Fast & Fun'),
  ('Ring a Ding', 'Fast & Fun'),
  ('كلم', 'Fast & Fun'),
  ('Piles!', 'Fast & Fun'),
  ('Brain Waves 2', 'Smart or Lucky'),
  ('Ghost Blitz', 'Fast & Fun'),
  ('Brain Waves', 'Smart or Lucky'),
  ('Kluster', 'Fast & Fun'),
  ('Sushi Dice', 'Fast & Fun'),
  ('Esquelet calavera Diablit', 'Fast & Fun'),
  ('Rhino Hero', 'Fast & Fun'),
  ('Loonacy', 'Fast & Fun'),
  ('SherLock', 'Fast & Fun'),
  ('لخبطة', 'Fast & Fun'),
  ('Cheese Master', 'Fast & Fun'),
  ('Ghost Blitz 2', 'Fast & Fun'),
  ('ليلى و الذيب', 'Fast & Fun'),
  ('Color Flush', 'Fast & Fun'),
  ('Tapple', 'Fast & Fun'),
  ('Taco', 'Fast & Fun'),
  ('Bandido', 'Family'),
  ('Cat Tower', 'Family'),
  ('For Sale', 'Take That'),
  ('Cluedo (NEW)', 'Family'),
  ('Dixit', 'Family'),
  ('Hues And Cues (New)', 'Family'),
  ('Love Letter Batman', 'Smart or Lucky'),
  ('777', 'Smart or Lucky'),
  ('Hula Hoo!', 'Family'),
  ('Levels', 'Family'),
  ('Spotlight', 'Kids'),
  ('مربعات المنطق', 'Kids'),
  ('Farm Rescue', 'Kids'),
  ('Chicky Boom', 'Kids'),
  ('Labyrinth', 'Kids'),
  ('Tinderblox', 'Kids'),
  ('Barbecubes', 'Kids'),
  ('Spot It!', 'Fast & Fun'),
  ('Dice Academy', 'Fast & Fun'),
  ('لعبة البرجر', 'Kids'),
  ('That’s Not A Hat', 'Smart or Lucky'),
  ('Break The Code', 'Smart or Lucky'),
  ('Rose Ceremony', 'Bluffing'),
  ('Skull', 'Bluffing'),
  ('Fiction', 'Smart or Lucky'),
  ('Ouch!', 'Smart or Lucky'),
  ('منو بالباب', 'Bluffing'),
  ('Get Bit Deluxe', 'Smart or Lucky'),
  ('بلاع البيزة', 'Smart or Lucky'),
  ('Port Royal', 'Smart or Lucky'),
  ('Gang Star', 'Smart or Lucky'),
  ('TimeLine Historical', 'Smart or Lucky'),
  ('Kings Gold', 'Smart or Lucky'),
  ('13 Beavers', 'Smart or Lucky'),
  ('0.01', 'Bluffing'),
  ('TimeLine Inventions', 'Smart or Lucky'),
  ('Diamant', 'Smart or Lucky'),
  ('The Mind', 'Smart or Lucky'),
  ('Cards Against Humanity', 'Party Games'),
  ('Monopolu (New)', 'Family'),
  ('Cash & Guns', 'Bluffing'),
  ('Fire Tower', 'Take That'),
  ('Smash Up Munchkin', 'Take That'),
  ('Survive The Island', 'Take That'),
  ('Munchkin', 'Take That'),
  ('Murdle', 'Family'),
  ('نذالة', 'Take That'),
  ('Deal Kuwait', 'Take That'),
  ('Dead Last', 'Bluffing'),
  ('Catan', 'Take That'),
  ('Unusual Suspects', 'Party Games'),
  ('عز القايلة', 'Take That'),
  ('القوة العسكرية الجديدة', 'Take That'),
  ('الليل الأسود', 'Take That'),
  ('الدائري الخامس', 'Take That'),
  ('New York Slice', 'Family'),
  ('Shifting Stones', 'Family'),
  ('Traitors Aboard!', 'Bluffing'),
  ('Side Effects', 'Take That'),
  ('Avalon', 'Bluffing'),
  ('Family Business', 'Take That'),
  ('مشنص', 'Bluffing'),
  ('Exploding Kittens', 'Take That'),
  ('سنور', 'Smart or Lucky'),
  ('Cosa Nostra Kuwait', 'Bluffing'),
  ('Skull King 3D Box', 'Take That'),
  ('اونو لا ترحم', 'Take That'),
  ('Mogel Motte', 'Bluffing'),
  ('Coup', 'Bluffing'),
  ('Sleeping Queens', 'Family'),
  ('Gloom', 'Take That'),
  ('Splendor', 'Family'),
  ('Hellapagos', 'Bluffing'),
  ('المخرب', 'Bluffing'),
  ('Rhino Hero Super Hero', 'Take That'),
  ('بدون كلام', 'Party Games'),
  ('Stella', 'Family'),
  ('فيلكا', 'Take That'),
  ('Things In Rings', 'Family'),
  ('The Crew', 'Smart or Lucky'),
  ('شريف', 'Bluffing'),
  ('King of Tokyo', 'Take That'),
  ('Push Push Penguin', 'Smart or Lucky'),
  ('One Night WereWolf', 'Bluffing'),
  ('Cheese Thief', 'Bluffing'),
  ('Decrypto', 'Smart or Lucky'),
  ('Speed Charades', 'Party Games'),
  ('Trio', 'Family'),
  ('Ticket To Ride', 'Dare to Discover'),
  ('Phantom', 'Dare to Discover'),
  ('Sounds Fishy', 'Party Games'),
  ('Secret Hitler', 'Bluffing'),
  ('Pac Man', 'Dare to Discover'),
  ('Tsuro', 'Family'),
  ('Muse', 'Party Games'),
  ('Codenames Harry Potter', 'Smart or Lucky'),
  ('Santorini', 'Dare to Discover'),
  ('Codenames', 'Smart or Lucky'),
  ('Codenames Pictures', 'Smart or Lucky'),
  ('Un Matched', 'Dare to Discover'),
  ('Pandamic', 'Dare to Discover'),
  ('Uno', 'Family'),
  ('Bloodborne', 'Dare to Discover'),
  ('Concept', 'Party Games'),
  ('واسطة', 'Dare to Discover'),
  ('Azul', 'Dare to Discover'),
  ('طنش', 'Dare to Discover'),
  ('Pylos', '2 Players'),
  ('When I Dream', 'Dare to Discover'),
  ('Uno 3D Box', 'Family'),
  ('Camel Up', 'Dare to Discover'),
  ('Potion Explosion', 'Dare to Discover'),
  ('Mysteruim', 'Dare to Discover'),
  ('Scotland Yard', 'Dare to Discover'),
  ('Ticket To Ride Rails&Sails', 'Dare to Discover'),
  ('Pictures', 'Dare to Discover'),
  ('Dimension', 'Dare to Discover'),
  ('Drop it', 'Dare to Discover'),
  ('Quoridor', 'Dare to Discover'),
  ('Quoridor Pacman', 'Dare to Discover'),
  ('I''m The Boss', 'Dare to Discover'),
  ('Pictionary', 'Party Games'),
  ('اتعرف عقالك', 'Challenge'),
  ('Sail', '2 Players'),
  ('Escape The Dark Castle', 'Dare to Discover'),
  ('Detective Club', 'Party Games'),
  ('Match Madness', 'Kids'),
  ('Uno Jambo', 'Dexterity'),
  ('Herd Mentality', 'Party Games'),
  ('Deception', 'Bluffing'),
  ('Harry Potter Labyrinth', 'Dare to Discover'),
  ('Tier auf Tier', 'Kids'),
  ('Jenga Fortnite', 'Kids'),
  ('Cinema Opening Night', 'Dexterity'),
  ('Fox', 'Dexterity'),
  ('Smash Up', 'Hard'),
  ('Dice Fruits', 'Fast & Fun'),
  ('CozyDen Tower', 'Kids'),
  ('Gobblet Gobblers', 'Kids'),
  ('انحش يالذيب', 'Dexterity'),
  ('جاكارو 4', 'Dexterity'),
  ('جاكارو لاعبين', 'Dexterity'),
  ('هند روسي', 'Dexterity'),
  ('داما', 'Dexterity'),
  ('Chess', 'Dexterity'),
  ('Jenga', 'Dexterity'),
  ('Flip 7', 'Smart or Lucky'),
  ('Uno Flip!', 'Family'),
  ('Suspend', 'Kids'),
  ('Cupcake', 'Kids'),
  ('Match & Toss', 'Kids'),
  ('Thunderroad', 'Dare to Discover'),
  ('Betrayal', 'Dare to Discover'),
  ('War chest', 'Hard'),
  ('Blood rage', 'Hard'),
  ('Above and below', 'Hard'),
  ('Clank!', 'Hard'),
  ('Small world', 'Hard'),
  ('Caverna the cave farmers', 'Hard'),
  ('Fallout', 'Hard'),
  ('catch the moon', 'Hard'),
  ('Demon worker', 'Hard'),
  ('Queendomino', 'Hard'),
  ('Black fleet', 'Hard'),
  ('Stuffed fables', 'Hard'),
  ('Castles of mosf king endwig', 'Hard'),
  ('Dead men tell no tales', 'Hard'),
  ('Habitats', 'Hard'),
  ('Vikings gone wild', 'Hard'),
  ('Combo fighter', 'Hard'),
  ('The bloody inm', 'Hard'),
  ('Robinson crusoe', 'Hard'),
  ('Plunder a pirates life', 'Hard'),
  ('Xcom', 'Hard'),
  ('Roll for the galaxy', 'Hard'),
  ('Carcassonne', 'Hard'),
  ('Police precinct', 'Hard'),
  ('Loony quest', 'Hard'),
  ('Dead men tell no tales Set', 'Hard'),
  ('Dominion', 'Hard'),
  ('Captain sonar', 'Hard'),
  ('Eter', 'Hard'),
  ('Carta magica', 'Hard'),
  ('Epic spell wars of the battle wizards', 'Hard'),
  ('Really loud libarians', 'Challenge'),
  ('Cv (what would happen if)', 'Hard'),
  ('Reef', 'Hard'),
  ('Dice forge', 'Hard'),
  ('Keep the heros out!', 'Hard'),
  ('Heat', 'Hard'),
  ('Dead of winter', 'Hard'),
  ('Champions of midgard', 'Hard'),
  ('Unfathomable', 'Hard'),
  ('Star wars unlock!', 'Hard'),
  ('Cosmic encounter', 'Hard'),
  ('Thunderstone quest', 'Hard'),
  ('Deep regets', 'Hard'),
  ('The quest for el dorado', 'Hard'),
  ('D&d bedlam in neverwinter', 'Hard'),
  ('Arcadia quest', 'Hard'),
  ('Tripple domino', 'Hard'),
  ('Meeple clrcus', 'Hard'),
  ('Sleeping gods', 'Hard'),
  ('Risk', 'Take That'),
  ('The Trial', 'Bluffing'),
  ('Dead Man''s Draw', 'Smart or Lucky'),
  ('New York 1901', 'Hard'),
  ('Feed The Kraken', 'Hard'),
  ('Uno Harry Potter', 'Family'),
  ('Tailor Master', '2 Players'),
  ('Telepathy', '2 Players'),
  ('ما بينا غريب', 'Chat'),
  ('Chutes and Ledders Peppa Pig (2)', 'Kids'),
  ('Black Sheep', 'Smart or Lucky'),
  ('Expression Puzzle Buidling Block', 'Kids'),
  ('Uno Skip Bo. 3D Box', 'Family'),
  ('من سبق لبق', 'Kids'),
  ('One Crown', 'Take That'),
  ('Radar', 'New'),
  ('Kezao', 'Fast & Fun'),
  ('Caution Signs', 'Party Games'),
  ('The Fox In The Forest', '2 Players'),
  ('المشاهير', 'Family'),
  ('Spy Guy Fantasy', 'Kids'),
  ('Spicy', 'Bluffing'),
  ('جاكارو 6', 'Dexterity'),
  ('Plakks', 'Dexterity'),
  ('ابطال و وحوش', 'Take That'),
  ('A Carnivore did it!', 'Party Games'),
  ('ماعونا وينه؟', 'Bluffing'),
  ('Osmosis', 'Smart or Lucky'),
  ('Lost Ruins of Arnak (SmallWorld)', 'Hard'),
  ('Small World (River World)', 'Hard'),
  ('Small World (Realms)', 'Hard'),
  ('جايبور', '2 Players'),
  ('Come on Bite me!', 'Bluffing'),
  ('LifeBoats', 'VIP'),
  ('جكني', 'Party Games'),
  ('مدير كبير', 'Party Games'),
  ('Mose Master', 'Party Games'),
  ('Good Cop Bad Cop', 'Bluffing'),
  ('سكرو', 'Smart or Lucky'),
  ('Tapple Arabic', 'Fast & Fun'),
  ('Pili Pili', 'Family'),
  ('CodeNames Duet', '2 Players'),
  ('جنجفة بدون اشكال', 'Family'),
  ('Brain Line', 'New'),
  ('حلقة قص موس دبوس', 'Fast & Fun'),
  ('مافيا لعبة الخداع', 'Bluffing'),
  ('Muffin Time', 'Take That'),
  ('البرلمان', 'Take That'),
  ('The Lord of the Rings', 'New'),
  ('Japani Name', 'New'),
  ('DogFight!', 'New'),
  ('Boss Battle Expanion', 'Hard'),
  ('Zombicide', 'Hard'),
  ('Panda Poker', 'Hard'),
  ('Escape The Dark Castle Scouge of the Undead Queen', 'Hard'),
  ('Escape The Dark Castle Blight of the Plangue Lord', 'Hard'),
  ('Cards vs gravity', 'Fast & Fun'),
  ('Sherlock Holmes', 'Hard'),
  ('الانتخابات', 'Take That'),
  ('Toy Story', 'Hard'),
  ('Horrified', 'Hard'),
  ('Tokaido', 'Hard'),
  ('Chronicles of Crime', 'Hard'),
  ('Memoir 44', 'Hard'),
  ('Agent Avenue (English)', 'VIP')
ON CONFLICT (title) DO UPDATE SET category = EXCLUDED.category;

COMMIT;
